name: Build & Push Docker Image

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Registrar QEMU (multi-arch)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # 3) Configurar Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4) Login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5) Build & Push multi-arch
      - name: Build and push multi-arch image
        uses: docker/build-push-action@v4
        with:
          context: .                       # contexto: raiz do repositório
          file: ./app.dockerfile          # <— aqui, apontando para o seu app.dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            wtmarketing/perplexica:latest
            wtmarketing/perplexica:${{ github.sha }}
